# Generated by Django 2.2 on 2019-04-14 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 4, 14, 17, 15, 53, 611414))),
                ('due_on', models.DateTimeField(default=datetime.datetime(2019, 4, 21, 17, 15, 53, 611414))),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('D', 'Done')], max_length=255)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskList')),
            ],
        ),
    ]
